# Training & model hyperparameters
data:
  midi_dir: d:/Music_Generator_Aiml/midi_songs
  processed_dir: outputs/processed
  sequence_length: 64  # Reduced from 100 to 64 for faster training
  val_split: 0.1
  test_split: 0.0

train:
  epochs: 10
  batch_size: 128
  learning_rate: 0.001

model:
  embedding_dim: 128  # Reduced from 256 to 128
  rnn_units: 256     # Reduced from 512 to 256
  transformer:
    num_layers: 2    # Reduced from 4 to 2
    d_model: 128     # Reduced from 256 to 128
    num_heads: 2     # Reduced from 4 to 2
    dff: 256         # Reduced from 512 to 256
    dropout: 0.1

generate:
  length: 200
  temperature: 1.0
